-- phpMyAdmin SQL Dump
-- version 3.4.11.1
-- http://www.phpmyadmin.net
--
-- Host: mysql1008.mochahost.com
-- Generation Time: Apr 14, 2020 at 04:47 PM
-- Server version: 5.6.45
-- PHP Version: 7.2.7

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `abdulgha_shikwa_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_ras_data`
--

CREATE TABLE IF NOT EXISTS `tbl_ras_data` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Product_Name` varchar(100) NOT NULL,
  `Product_Brand` varchar(100) NOT NULL,
  `Product_Category` varchar(45) NOT NULL,
  `Country_Origin` varchar(45) NOT NULL,
  `City_Origin` varchar(45) NOT NULL,
  `Risk_Type` varchar(45) NOT NULL,
  `Description` varchar(500) DEFAULT NULL,
  `Image_Path` varchar(500) DEFAULT NULL,
  `transaction_hash` varchar(100) NOT NULL,
  `Model` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=153 ;

--
-- Dumping data for table `tbl_ras_data`
--

INSERT INTO `tbl_ras_data` (`Id`, `Product_Name`, `Product_Brand`, `Product_Category`, `Country_Origin`, `City_Origin`, `Risk_Type`, `Description`, `Image_Path`, `transaction_hash`, `Model`) VALUES
(1, 'Toucan Light', 'Simond', 'Hobby/sports equipment', 'Taiwan', '', 'Injuries', 'Injuries\r\nThe belay device can lock without control and climbers can get blocked. This can lead to de-stabilisation and fall of the climber and  the belayer could not be able to progressively brake. At the same time, the rope supplement not recovered through the belay device can increase the fall distance of the climber.\r\nIn such case, the entire belaying chain can also break due to additional stress or transmit the kinetic energy of a fall abruptly to the falling body, causing serious injury by', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28916-1s.jpg', '', NULL),
(2, 'Oxboard Go', 'Guangzhou Ji Yin Hong Ba Electronic, Oxboard  ', 'Hobby/sports equipment', 'Nepal', '', 'Burns, Fire', 'Burns, Fire\r\nThe charging circuit has no cut-off switch.\r\nThe battery can consequently overcharge and overheat which may lead to a fire or burns.\r\n\r\nThe product does not comply with the requirements of the Machinery Directive and the relevant European standards EN 62133, EN 60335-1 and EN 61558.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28817-1s.jpg', '', NULL),
(3, 'Unknown', 'Unknown', 'Jewellery', 'China', '', 'Chemical', 'Chemical\r\nThe earrings release an excessive amount of nickel (measured value: 13.3 μg/cm²/week).\r\nNickel is a strong sensitiser and can cause allergic reactions if present in articles that come into direct and prolonged contact with the skin.\r\n\r\nThe product does not comply with the REACH Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28961-1s.jpg', '', NULL),
(4, 'Unknown', 'Ibero', 'Jewellery', 'China', '', 'Chemical', 'Chemical\r\nThe pendants contain an excessive amount of cadmium (measured value up to 95% by weight).\r\nCadmium is harmful to human health because it accumulates in the body, can damage organs and it may cause cancer.\r\n\r\nThe product does not comply with the REACH Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28972-1s.jpg', '', NULL),
(5, '3in1 LASER & LED LIGHT & KEY CHAIN', 'YQ ', 'Laser pointers', 'China', '', 'Damage to sight', 'Damage to sight\r\nThe laser beam is too powerful.\r\nDirect viewing of the laser beam could cause damage to sight.\r\n\r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28978-1s.jpg', '', NULL),
(6, 'MX-5', 'Mazda', 'Motor vehicles', 'Japan', '', 'Injuries', 'Injuries\r\nThe underbody panelling may be inadequately attached.\r\nAs a result, it could become detached and fall onto the road, potentially damaging the tyres and posing a risk to the following traffic.', NULL, '', NULL),
(7, 'BETAMOTOR', 'BETA', 'Motor vehicles', 'Italy', '', 'Injuries', 'Injuries\r\nThe two rear shock absorber fastening screws may be defective and could break.\r\nConsequently, the rear of the motorcycle would be lowered, increasing the risk of an accident.', NULL, '', NULL),
(8, 'Telescopic ladder - Giraffe 3.88', 'Batavia', 'Other', 'The Netherlands', '', 'Injuries', 'Injuries\r\nThe angular rotation of the ladder is too high, affecting the stability of the user.\r\nThe user might consequently lose balance and fall from the ladder.\r\n\r\n\r\nThe product does not comply with the relevant European Standard EN 131.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28985-1s.jpg', '', NULL),
(9, 'Fingermalfarben', 'Klecksi', 'Toys', 'Germany', '', 'Microbiological', 'Microbiological\r\nThe toy contains aerobic mesophilic bacteria (measured value up to: 120000 cfu/g) and the presence of Pseudomonas aeruginosa has been detected.\r\nIf played with by children with compromised or weakened immunity, the product may cause infection or irritation.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28970-1s.jpg', '', NULL),
(10, 'Unknown', 'Plasto', 'Toys', 'Finland', '', 'Choking', 'Choking\r\nThe ball of the plane-shaped mould can be easily detached, generating a small part.\r\nA small child may put it in the mouth and choke.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28971-1s.jpg', '', NULL),
(11, 'Microphone smart set', 'Unknown', 'Toys', 'China', '', 'Damage to hearing', 'Damage to hearing\r\nThe sound pressure level of the toy is too high.\r\nIt could cause damage to hearing.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28974-1s.jpg', '', NULL),
(12, 'Pantys', 'Tchibo', 'Clothing, textiles and fashion items', 'Sri Lanka', '', 'Chemical', 'Chemical\r\nThe product releases an excessive amount of nickel (calculated value: 87 µg/cm2/week).\r\nNickel is a strong sensitizer and causes allergic reactions if present in articles that come into direct and prolonged contact with the skin.\r\n\r\nThe product does not comply with the REACH Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28836-1s.jpg', '', NULL),
(13, 'Unknown', 'I.M.A ', 'Clothing, textiles and fashion items', 'Greece', '', 'Injuries', 'Injuries\r\nThe product contains cords with free ends at the upper chest area.\r\nThe cords can become trapped during activities of the child and cause serious injuries.\r\n\r\nThe product does not comply with the relevant European standard EN 14682. ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28962-1s.jpg', '', NULL),
(14, 'Unknown', 'Oute Kids', 'Clothing, textiles and fashion items', 'Italy', '', 'Injuries', 'Injuries\r\nThere are long drawstrings to be tied at the back of the T-shirt.\r\nThey may become trapped during various activities of a child, leading to injury. \r\n\r\nThe product does not comply with the relevant European Standard EN 14682.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28980-1s.jpg', '', NULL),
(15, 'Unknown', 'Danshan/Taozhuang', 'Clothing, textiles and fashion items', 'China', '', 'Injuries', 'Injuries\r\nThe cords in the upper chest area of garment are too long.\r\nThe cords can become trapped during various activities of a child, leading to injuries.\r\n\r\nThe product does not comply with the relevant European Standard EN 14682.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28981-1s.jpg', '', NULL),
(16, 'Skoraja pomosh', 'Horse Health', 'Cosmetics', 'Russian Federation', '', 'Chemical', 'Chemical\r\nAccording to the ingredients list, the product contains a mixture of the preservatives methylchloroisothiazolinone and methylisothiazolinone (MCI/MI), which is not permitted in leave-on cosmetic products.\r\nDermal contact with MCI and MI containing products can provoke allergic contact dermatitis to sensitised persons.\r\n\r\nThe product does not comply with the Cosmetic Products Regulation.\r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28937-1s.jpg', '', NULL),
(17, 'Fruit crystal mud', 'New arrival ', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe migration of boron from the toy slime is too high (measured value up to 1917 mg/kg).\r\n\r\nDue to its characteristic form, colour, appearance and size, the product may be mistaken for foodstuff.\r\nThis may lead a small child to put the product in the mouth, which could cause the kid to swallow the slime.\r\nIngestion or contact with an excessive quantity of boron may harm the health of children by damaging their reproductive system. \r\n\r\nThe product does not comply with the requirements o', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w34/2019-w34_28387-1s.jpg', '', NULL),
(18, '', 'Ibero', 'Jewellery', 'People''s Republic of China', '', 'Chemical', 'Chemical\r\nThe product contains an excessive amount of cadmium  and lead (measured values: 0,98 % and 0,098 % by weight, respectively).\n\n / Cadmium is harmful to human health because it accumulates in the body, can damage the kidney and bones, and it may cause cancer.\n\nLead is harmful to human health, accumulates in the body, can cause developmental neurotoxicity and may also affect breast-fed or unborn children.\n\nThe product does not comply with the REACH Regulation.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001978-f.jpg', '', NULL),
(19, 'NEW HIGH-TECH ULTRA-GLOWLITE LED KEY CHAIN; ZSeblámpa', '', 'Laser pointers', 'People''s Republic of China', '', 'Damage to sight', 'Damage to sight\r\nThe laser beam is too powerful. Direct viewing of the laser beam could cause damage to sight. /  \r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001994-f.jpg', '', NULL),
(20, 'Yaris', 'Toyota', 'Motor vehicles', 'France', '', 'Injuries', 'Injuries\r\nThe vehicles might have been fitted with an inappropriate replacement airbag inflator.\n\nConsequently, in the event of an accident the airbag might not properly deploy, increasing the risk of injuries.\n /   \r\n ', NULL, '', NULL),
(21, 'Camry', 'Toyota', 'Motor vehicles', 'Japan', '', 'Injuries', 'Injuries\r\nIn the rear dual mode locking seat belt assemblies, the spring in the webbing sensor locking mechanism might have been installed in an incorrect position.\n\nConsequently, the spring might impair the locking of the seat belt, thus increasing the risk of injuries in the event of an accident.\n /  \r\n ', NULL, '', NULL),
(22, 'Citaro, Intouro, Setra, Tourismo', 'Evobus', 'Motor vehicles', 'Germany', '', 'Fire', 'Fire\r\nFaulty fitting of the fuel line could give rise to a fire risk.  / Not stated\r\n ', NULL, '', NULL),
(23, 'Fairy Egg / Growing Pet', 'Tasso', 'Toys', 'People''s Republic of China', '', 'Choking, Injuries', 'Choking, Injuries\r\nThe toy can be put into the mouth and swallowed by children. As the toy expands, it can cause fatal occlusion of the respiratory track or intestinal blockage of small children. / The product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001969-f.jpg', '', NULL),
(24, 'MIX BEAD BALLS SQUEEZE BULB', '', 'Toys', 'People''s Republic of China', '', 'Chemical, Choking', 'Chemical, Choking\r\nThe fake bulb screw of the toy can easily detach during use, releasing the internal flashing capsule with button batteries. This capsule can easily break, leaving the button batteries accessible.\n\nA child could put them in the mouth, which could cause damage to the child’s gastrointestinal tract or choking. \n / The product does not comply with the requirements of the Toy Safety Directive and the relevant European standard  EN 62115. \r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001983-f.jpg', '', NULL),
(25, 'Adventskalender - Calendrier de l''avent', '', 'Toys', 'People''s Republic of China', '', 'Choking', 'Choking\r\nThe white mouthpiece of the toy trumpet, in the calendar drawer 9, can easily detach.\n\nIt may do so while a child has the trumpet in the mouth, leading the child to choke. / The product does not comply with the requirements of Toy Safety Directive and the relevant European standard EN 71-1. \r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10002008-f.jpg', '', NULL),
(26, 'Játékszer', 'Fashion Girl/Sweet ', 'Toys', 'People''s Republic of China', '', 'Chemical', 'Chemical\r\nThe plastic material of the product contains an excessive amount of bis(2-ethylhexyl) phthalate (DEHP) and dibutyl phthalate (DBP) (measured values: 35 % and 0.22 % by weight, respectively).\n \nThese phthalates may harm the health of children, causing possible damage to their reproductive system.\n\n / The product does not comply with the REACH Regulation.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10002022-f.jpg', '', NULL),
(27, 'Plüss játék állat', 'Ciudad Sion Toys', 'Toys', 'People''s Republic of China', '', 'Choking', 'Choking\r\nThe eyes of the toy can easily detach, generating small parts.\n\nA small child may put them in the mouth and choke. / The product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10002012-f.jpg', '', NULL),
(28, '', 'Elegant Girl/Charm Lovely Girl', 'Toys', 'People''s Republic of China', '', 'Chemical', 'Chemical\r\nThe plastic material of the product contains an excessive amount of bis(2-ethylhexyl) phthalate (DEHP) and dibutyl phthalate (DBP)(measured values: 41 % and 0.17 % by weight, respectively). \n\nThese phthalates may harm the health of children, causing possible damage to their reproductive system. / The product does not comply with the REACH Regulation.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10002009-f.jpg', '', NULL),
(29, 'Fishing Game', 'Jumini', 'Toys', 'People''s Republic of China', '', 'Choking', 'Choking\r\nSmall pieces (the metal part) may detach from the toy. A small child may put them in the mouth and choke. / The product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001977-f.jpg', '', NULL),
(30, '', '4-OK, EBITA GIRL', 'Clothing, textiles and fashion items', 'Turkey', '', 'Strangulation', 'Strangulation\r\nThe product has functional cords with free ends at the neck area.\n\nThese cords can become trapped during various activities of a child, leading to strangulation.\n\n / The product does not comply with the relevant European standard 14682.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001965-f.jpg', '', NULL),
(31, '', 'Two in a castle', 'Clothing, textiles and fashion items', 'Greece', '', 'Strangulation', 'Strangulation\r\nThe product has long functional cords with free ends in the neck area.\n\nThese cords can become trapped during various activities of a child, leading to strangulation. / \n\nThe product does not comply with the relevant European Standard EN 14682.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001981-f.jpg', '', NULL),
(32, '', 'VICTEX', 'Clothing, textiles and fashion items', 'Turkey', '', 'Injuries, Strangulation', 'Injuries, Strangulation\r\nThe product has long drawstrings with free ends in the neck and waist area. \n\nThese drawstrings can become trapped during various activities of a child, leading to strangulation or injuries. / The product does not meet the relevant European Standard EN 14682.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001987-f.jpg', '', NULL),
(33, '', 'AK Giyim', 'Clothing, textiles and fashion items', 'Turkey', '', 'Injuries, Strangulation', 'Injuries, Strangulation\r\nThe product has long drawstrings with free ends at the neck and waist area.\n\nThese drawstrings can become trapped during various activities of a child, leading to strangulation or injuries.\n\n / The product does not comply with the relevant European standard 14682.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001986-f.jpg', '', NULL),
(34, '', 'Hieuey', 'Clothing, textiles and fashion items', 'Turkey', '', 'Injuries, Strangulation', 'Injuries, Strangulation\r\nThe product has long drawstrings with free ends in the neck and waist area.\n\nThese drawstrings can become trapped during various activities of a child, leading to strangulation or injuries.\n / The product does not meet the relevant European Standard EN 14682.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001985-f.jpg', '', NULL),
(35, '', 'Findik', 'Clothing, textiles and fashion items', 'Turkey', '', 'Choking', 'Choking\r\nThe small decorative elements on the product can be easily detached.\n\nA small child may put them in the mouth and choke. /  \r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001984-f.jpg', '', NULL),
(36, '', 'WEIVE', 'Clothing, textiles and fashion items', 'Turkey', '', 'Choking', 'Choking\r\nPebbles can be easily detached, generating small parts. A small child can put the small part in the mouth and choke on it.  /  \r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001989-f.jpg', '', NULL),
(37, '', 'Oute kids', 'Clothing, textiles and fashion items', 'Italy', '', 'Strangulation', 'Strangulation\r\nThere are drawstring in the neck area of the of the blouse hood.\nThe cords could become trapped during various activities of a child and lead to strangulation. / The product does not comply with the relevant European standard EN 14682.\n\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001990-f.jpg', '', NULL),
(38, 'HENNA HAIR COLOR', 'Henna Vital', 'Cosmetics', 'India', '', 'Chemical', 'Chemical\r\nThe product contains sodium perborate (calculated value: 12,8 %), which releases boron (measured value 1,7 %) and an excessive amount of p-phenylenediamine (PPD)(measured value > 7.3%, > 2 % in final solution).\n\nContact with an excessive quantity of boron may harm the health of children by damaging their reproductive system or damage the unborn child. PPD is an extreme skin sensitiser and can trigger allergic contact dermatitis\n\n / The product does not comply with the Cosmetic Products', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001964-f.jpg', '', NULL),
(39, 'Candles with Wood Wicks', 'DW', 'Decorative articles', 'United States', '', 'Asphyxiation, Chemical', 'Asphyxiation, Chemical\r\nThe candle releases an excessive amount of smoke. \n / A person could inadvertently breathe in the toxic smoke, which might lead to poisoning or asphyxiation through carbon monoxide exposure.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001967-f.jpg', '', NULL),
(40, 'AC Adapter with USB Slot', 'Durata', 'Electrical appliances and equipment', 'People''s Republic of China', '', 'Electric shock', 'Electric shock\r\nThe product''s electrical strength and clearance/creepage distances  in the printed circuit board and between the primary and secondary circuits are insufficient. Additionally, the insulating capacitor is not sufficient. \n\nConsequently, the accessible USB port might become live, increasing the risk of the user receiving an electric shock. / The product does not comply with the requirements of the Low Voltage Directive and the relevant European standard 60950.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001997-f.jpg', '', NULL),
(41, '', 'Luxcell', 'Electrical appliances and equipment', 'People''s Republic of China', '', 'Electric shock', 'Electric shock\r\nThe product''s electrical strength and clearance/creepage distances in the printed circuit board and between the primary and secondary circuits are insufficient. Additionally, the insulating capacitor is not sufficient. \n\nConsequently, the accessible USB ports might become live, increasing the risk of the user receiving an electric shock. / The product does not comply with the requirements of the Low Voltage Directive and the relevant European standard 60950.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10002004-f.jpg', '', NULL),
(42, '', 'Qihang', 'Electrical appliances and equipment', 'People''s Republic of China', '', 'Electric shock', 'Electric shock\r\nThe product''s electrical strength and clearance/creepage distances in the printed circuit board and between the primary and secondary circuits are insufficient. Additionally, the insulating capacitor is not sufficient. \n\nConsequently, the accessible USB port might become live, increasing the risk of the user receiving an electric shock. / The product does not comply with the requirements of the Low Voltage Directive and the relevant European standard 60950.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10002002-f.jpg', '', NULL),
(43, '', 'EMC', 'Electrical appliances and equipment', 'People''s Republic of China', '', 'Electric shock', 'Electric shock\r\nThe product''s electrical strength and clearance/creepage distances in the printed circuit board and between the primary and secondary circuits are insufficient. Additionally, the insulating capacitor is not sufficient. \n\nConsequently, the accessible USB port might become live, increasing the risk of the user receiving an electric shock. / The product does not comply with the requirements of the Low Voltage Directive and the relevant European standard 60950.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10002000-f.jpg', '', NULL),
(44, '', '', 'Electrical appliances and equipment', 'People''s Republic of China', '', 'Electric shock', 'Electric shock\r\nThe product''s electrical strength and clearance/creepage distances in the printed circuit board and between the primary and secondary circuits are insufficient.\n\nConsequently, the accessible USB ports might become live, increasing the risk of the user receiving an electric shock. / The product does not comply with the requirements of the Low Voltage Directive and the relevant European standard 60950.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001999-f.jpg', '', NULL),
(45, 'Mitre Saw - Circular Bench Saw', 'Power Craft', 'Machinery', 'People''s Republic of China', '', 'Cuts, Damage to sight', 'Cuts, Damage to sight\r\nThe saw can move from its position during operation and its blade guard does not properly lock.\n\nConsequently, the user could get in contact with the turning blade and become injured.\n\nAlso, when tilted at 45 degrees, the blade can touch the product''s aluminium table. \n\nAs a result, it will cut it and propel its material towards an unprotected user, who might suffer of injuries in the body or face. / The product does not comply with the requirements of the Machinery Direct', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001975-f.jpg', '', NULL),
(46, 'Magnet glued ', '', 'Decorative articles', 'Unknown', '', 'Choking', 'Choking\r\nThe product, due to its characteristic form, colour and size, may be mistaken for foodstuff. Small parts can be easily detached from the product.\nThis may lead especially children to put the small parts in the mouth and choke on them.\n / The product does not comply with the requirements of the Food Imitating Products Directive.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/blobs2fs/2020/2020-w1/2020-w1-10001991-f.jpg', '', NULL),
(47, '208', 'Peugeot', 'Motor vehicles', 'France', '', 'Injuries', 'Injuries\r\nScrews anchoring the alternator and the air conditioning compressor may not be tightened to the correct torque.\r\nAs a result, the alternator or the compressor could detach from the engine and fall onto the road.\r\n', NULL, '', NULL),
(48, 'Duster', 'Dacia', 'Motor vehicles', 'Romania', '', 'Injuries', 'Injuries\r\nA software problem could affect the stop-start system.\r\nThe stop-start system could consequently fail.\r\n', NULL, '', NULL),
(49, 'C3 IV', 'Citroën', 'Motor vehicles', 'France', '', 'Injuries', 'Injuries\r\nScrews anchoring the alternator and the air conditioning compressor may not be tightened to the correct torque.\r\nAs a result, the alternator or the compressor could detach from the engine and fall onto the road.', NULL, '', NULL),
(50, 'C4 Picasso,C4,DS4,C5,DS4', 'Citroën', 'Motor vehicles', 'France', '', 'Injuries', 'Injuries\r\nOverheating of the engine may occur due to a problem with the engine control software.\r\nOverheating of the engine may lead to engine failure.', NULL, '', NULL),
(51, 'S9', 'Aixam', 'Motor vehicles', 'France', '', 'Injuries', 'Injuries\r\nA defective control relay might prevent the engine from being switched off.\r\nThis could cause the engine to overheat leading to a fire.', NULL, '', NULL),
(52, 'Flavia', 'Lancia', 'Motor vehicles', 'United States', '', 'Injuries', 'Injuries\r\nAn electrical overload may occur in the airbag control unit.\r\nThis could lead to the active headrests not being activated in the event of an accident.', NULL, '', NULL),
(53, 'Zoé', 'Renault', 'Motor vehicles', 'France', '', 'Injuries', 'Injuries\r\nA component in the parking brake mechanism may be defective.\r\nThere is a risk of a sudden loss of the park function.', NULL, '', NULL),
(54, 'Grandland', 'Opel', 'Motor vehicles', 'Germany', '', 'Injuries', 'Injuries\r\nOil can enter the intake circuit of the engine.\r\nThis can lead to engine failure.', NULL, '', NULL),
(55, 'Sprinter', 'Mercedes-Benz', 'Motor vehicles', 'Germany', '', 'Injuries', 'Injuries\r\nCorrosion of the gas-pressure tank may occur.\r\nThis could lead to the tank bursting. \r\n', NULL, '', NULL),
(56, 'LINDA HERMOSA SIRENA', 'Unknown', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe plastic material of the doll contains bis (2-ethylhexyl) phthalate (DEHP) (measured value 16.14% by weight).\r\nThis phthalate may harm the health of children, causing possible damage to the reproductive system.\r\n\r\nThe product does not comply with the REACH Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24788-1s.jpg', '', NULL),
(57, 'Pretty angels', 'Clown', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe plastic material of the doll contains bis (2-ethylhexyl) phthalate (DEHP) (measured value 21.1% by weight).\r\nThis phthalate may harm the health of children, causing possible damage to the reproductive system.\r\n\r\nThe product does not comply with the REACH Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24794-1s.jpg', '', NULL),
(58, 'Badminton set', 'New Sports ', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe handles of the rackets contain di-(2-ethylhexyl) phthalate (DEHP) (measured value: 17.4% by weight).\r\nThis phthalate is toxic to reproduction.\r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24686-1s.jpg', '', NULL),
(59, 'Porsche Drivers Selection', 'Porsche', 'Toys', 'Poland', '', 'Choking', 'Choking\r\nThe wheels and axle of the toy car can be easily detached, generating small parts.\r\nA small child may put the small parts in the mouth and choke on them.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24793-1s.jpg', '', NULL),
(60, 'Unknown', 'Fabrizio', 'Clothing, textiles and fashion items', 'China', '', 'Chemical', 'Chemical\r\nThe amount of chromium (VI) in the leather is too high (measured value: 13.6 mg/kg).\r\nChromium (VI) is sensitising and may trigger allergic reactions.\r\n\r\nThe product does not comply with the REACH Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24718-1s.jpg', '', NULL),
(61, 'Imperméable T500', 'KIPSTA', 'Clothing, textiles and fashion items', 'Vietnam', '', 'Strangulation', 'Strangulation\r\nThe cord in the neck area is too long.\r\nIt may become trapped during various activities of a child, leading to strangulation.\r\n\r\nThe product does not comply with the relevant European standard EN 14682.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24755-1s.jpg', '', NULL),
(62, 'Unknown', 'RESERVED', 'Clothing, textiles and fashion items', 'China', '', 'Injuries', 'Injuries\r\nThe drawstrings in the waist area are too long.\r\nThey can become trapped during various activities of a child, leading to injuries.\r\n\r\nThe product does not comply with the relevant European Standard EN 14682.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24783-1s.jpg', '', NULL),
(63, 'Unknown', 'FRESH LINE', 'Cosmetics', 'Greece', '', 'Chemical, Choking', 'Chemical, Choking\r\nDue to their characteristic form, appearance, colour and size, these products may be mistaken for a foodstuff and attract the curiosity of children.\r\nSmall parts can be easily detached from the product and this may lead children to put them in the mouth and choke.\r\n\r\nThe product does not comply with the cosmetics Regulation and with the requirements of the Food imitating Products Directive. ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24774-1s.jpg', '', NULL),
(64, 'Unknown', 'FRESH& PERSONAL COSMETICS', 'Cosmetics', 'Greece', '', 'Chemical, Choking', 'Chemical, Choking\r\nDue to their characteristic form, appearance, colour and size, this product may be mistaken for a foodstuff and attract the curiosity of children.\r\nSmall parts can be easily detached from the product and this may lead children to put them in the mouth and choke.\r\n\r\nThe product does not comply with the cosmetics Regulation and with the requirements of the Food imitating Products Directive. ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24775-1s.jpg', '', NULL),
(65, 'Крем-бальзам "Целитель"', 'Unknown', 'Cosmetics', 'Ukraine', '', 'Chemical', 'Chemical\r\nThe cream contains a mixture of methylisothiazolinone and methylchloroisothiazolinone (MI/MCI) (measured value: 0.0003%).\r\nDermal contact with MCI and MI containing products can provoke allergic contact dermatitis to sensitised persons.\r\n\r\nThe product does not comply with the Cosmetic Products Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24801-1s.jpg', '', NULL),
(66, 'Whitening Body Lotion', 'Clinic Clear', 'Cosmetics', 'Togo', '', 'Chemical', 'Chemical\r\nThe product contains hydroquinone (measured value 3.1% by weight).\r\nHydroquinone can cause skin irritation and dermatitis.\r\n\r\nThe product does not comply with the Cosmetic Products Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24781-1s.jpg', '', NULL),
(67, 'Half Cast', '2 tees', 'Cosmetics', 'Nigeria', '', 'Chemical', 'Chemical\r\nThe product contains hydroquinone (measured value 2.4% by weight).\r\nHydroquinone can cause skin irritation and dermatitis. \r\n\r\nThe product does not comply with the Cosmetic Products Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24782-1s.jpg', '', NULL),
(68, '24 PURE', 'DORALL Collection', 'Cosmetics', 'India', '', 'Chemical', 'Chemical\r\nThe cream contains methylchloroisothiazolinone (MCI) and methylisothiazolinone (MI).\r\nDermal contact with MCI and MI containing products can provoke allergic contact dermatitis to sensitised persons.\r\n\r\nThe product does not comply with the Cosmetic Products Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24784-1s.jpg', '', NULL),
(69, 'Crème Éclaircissante', 'Maxi Light', 'Cosmetics', 'Ivory Coast', '', 'Chemical', 'Chemical\r\nThe product contains kojic acid (measured value: 0.95% by weight).\r\nKojic acid can induce skin sensitisation.\r\n\r\nThe product does not comply with the Cosmetics Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w14/2018-w14_24779-1s.jpg', '', NULL),
(70, 'Dr Grill', 'Planta', 'Kitchen/cooking accessories', 'China', '', 'Burns, Fire', 'Burns, Fire\r\nThe grill pit is insufficiently deep.\r\nBurning parts of fuel (charcoal) can easily fall out of the barbecue grill causing fire or burns to users or children near the barbecue.\r\n\r\nThe product does not comply with the relevant European standard EN 1860-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28213-1s.jpg', '', NULL),
(71, 'LED 200 BOMBILLAS', 'Unknown', 'Lighting chains', 'China', '', 'Electric shock', 'Electric shock\r\nThe mains cable is not properly anchored and can detach.\r\nAs a consequence, live parts may become accessible, which could result an electric shock.\r\n\r\nThe product does not comply with the the requirements of the Low Voltage Directive and the relevant European standard EN 60598. ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28217-1s.jpg', '', NULL),
(72, 'RPGT noël guirlande lumineuse LED', 'Foshan Youcheng Electric appliance', 'Lighting chains', 'China', '', 'Electric shock', 'Electric shock\r\nThe pin on the lighting chain plug (intended to be powered at extra-low safety voltages) fits into the network connector under dangerous voltage (low voltage).\r\nThe lighting chain may therefore be under a voltage for which the insulation is insufficient, which may cause an electric shock. \r\n\r\nThe product does not comply with the requirements of the Low Voltage Directive and the relevant European Standard 60598.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_27996-1s.jpg', '', NULL),
(73, 'C-Class, GLC F-Cell', 'Mercedes-Benz', 'Motor vehicles', 'Germany', '', 'Injuries', 'Injuries\r\nThe sleep mode functionality of the electronic parking brake within the electronic stability programme (ESP) software may be defective.\r\nAs a result, the brake lights may be permanently activated or the ESP function could be deactivated, increasing the risk of an accident.', NULL, '', NULL),
(74, 'Combo', 'Opel', 'Motor vehicles', 'Spain', '', 'Injuries', 'Injuries\r\nPossible misalignment of the ratchet on the handbrake lever latching mechanism.\r\nAs a result the handbrake may not engage or could disengage by itself, increasing the risk of an accident. ', NULL, '', NULL),
(75, 'SB4003', 'Stedele', 'Motor vehicles', 'Germany', '', 'Injuries', 'Injuries\r\nThe wheel nuts may be inadequate.\r\nAs a result the wheels may come loose, increasing the risk of an accident.', NULL, '', NULL),
(76, 'Giulia, Stelvio', 'Alfa Romeo', 'Motor vehicles', 'Italy', '', 'Injuries', 'Injuries\r\nThe seat guides may be inadequate and the seats may be wrongly positioned.\r\nAs a result the seats could become detached in motion, increasing the risk of an accident.', NULL, '', NULL),
(77, 'RAV4, Corolla, UX, ES', 'Toyota, Lexus', 'Motor vehicles', 'Japan', '', 'Injuries', 'Injuries\r\nThe emergency calling system may not be correctly installed.\r\nAs a consequence, the emergency calling system will not activate automatically in the case of an accident.', NULL, '', NULL),
(78, 'Crossland X', 'Opel', 'Motor vehicles', 'Spain', '', 'Injuries', 'Injuries\r\nThe rear axle bolts may be defective and could break.\r\nThis could lead to loss of control over the vehicle, increasing the risk of an accident.\r\n', NULL, '', NULL),
(79, 'Accord, Civic and Odyssey', 'Honda', 'Motor vehicles', 'Canada', '', 'Injuries', 'Injuries\r\nThe replacement service parts from the previous recall may be defective.\r\nIn the event of the passenger frontal airbag being deployed, the excessive internal pressure may cause the inflator body to rupture and metal fragments may pass through the cushion material causing injury to the occupants.', NULL, '', NULL),
(80, 'Gas & CO detector', 'Cabletech', 'Other', 'China', '', 'Asphyxiation', 'Asphyxiation\r\nThe device is not sufficiently sensitive with respect to the detection of carbon monoxide.\r\nThe product poses a risk of CO poisoning.\r\n\r\nThe product does not comply with the relevant European standard EN 50291.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28211-1s.jpg', '', NULL),
(81, 'Gas & CO detector', 'Cabletech', 'Other', 'China', '', 'Asphyxiation', 'Asphyxiation\r\nThe device is not sufficiently sensitive with respect to the detection of carbon monoxide.\r\nThe product poses a risk of CO poisoning.\r\n\r\nThe product does not comply with the relevant European standard EN 50291.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28212-1s.jpg', '', NULL),
(82, 'Sling Unlimited 4 in 1', 'Mini Monkey', 'Childcare articles and children''s equipment', 'The Netherlands', '', 'Injuries', 'Injuries\r\nThe attachment system can easily slip and the product can break. A child can consequently fall out of the carrier and suffer injuries.\r\nMoreover, the product lacks a head support for the child which may lead to head injuries.\r\n\r\nThe product does not comply with the relevant European standard EN 13209.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28154-1s.jpg', '', NULL),
(83, 'Transformer X-Bag', 'Concord', 'Childcare articles and children''s equipment', 'Germany', '', 'Injuries', 'Injuries\r\nIn the case of an impact, the back-rest could move down.\r\nThis could cause injury to the child''s head or cervical spine. The child could consequently also slip through the safety belt and suffer injuries.\r\n\r\nThe product does not comply with Regulation UNECE No 44-04.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28262-1s.jpg', '', NULL),
(84, 'Unknown', 'Automax', 'Childcare articles and children''s equipment', 'China', '', 'Injuries', 'Injuries\r\nThe plastic shell of the base can break in the event of a car accident or sudden and violent braking of the vehicle, impairing the safety of the child.\r\nMoreover, the crack creates sharp edges that could damage the seat belt, preventing effective restraint of the child.\r\n\r\nThe product does not comply with Regulation UNECE No 44-04.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28261-1s.jpg', '', NULL),
(85, 'Flash light spinning top', 'Wonder kids', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe toy''s casing can easily break, causing the button batteries to become accessible.\r\nA child may put the batteries in the mouth, which could cause damage to the child’s gastrointestinal tract if swallowed.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 62115.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28179-1s.jpg', '', NULL),
(86, 'CREEPY OOZE SLIME', 'Unknown', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe migration of boron from the toy slime is too high (measured value up to 839 mg/kg).\r\nIngestion or contact with an excessive quantity of boron may harm the health of children by damaging their reproductive system. \r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-3.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28216-1s.jpg', '', NULL),
(87, 'Zabawka Pluszowa', 'Unknown', 'Toys', 'China', '', 'Choking', 'Choking\r\nSmall parts (elastic bands) can be easily detached from the toy.\r\nA child may put the small part in the mouth and choke on it.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28214-1s.jpg', '', NULL),
(88, 'Optimus prime', 'Transformers', 'Toys', 'China', '', 'Damage to hearing', 'Damage to hearing\r\nThe sound pressure level of the helmet''s speakers is too high.\r\nIt could cause damage to hearing.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28242-1s.jpg', '', NULL),
(89, 'ΠΡΙΤΣΑ - Slime', 'Unknown', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe migration of boron from the toy slime is too high (measured value up to 499 mg/kg).\r\nIngestion or contact with an excessive quantity of boron may harm the health of children by damaging the reproductive system. \r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-3.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28069-1s.jpg', '', NULL),
(90, 'Microwaveable toys', 'Kuddleez', 'Toys', 'United Kingdom', '', 'Burns', 'Burns\r\nWhen heated up, the material of the soft toy can easily smoulder.\r\nThe product can consequently cause burns if in contact with the skin. \r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28206-1s.jpg', '', NULL),
(91, 'Beauty', 'Unknown', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe plastic material of the product contains an excessive amount of bis(2-ethylhexyl) phthalate (DEHP) and dibutyl phthalate (DBP) (measured values up to 32 % and 17 % by weight, respectively).\r\nThese phthalates may harm the health of children, causing possible damage to their reproductive system.\r\n\r\nThe product does not comply with the REACH Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28218-1s.jpg', '', NULL),
(92, 'WHOOPEE PUTTY', 'Toi-Toys', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe migration of boron from the toy slime is too high (measured value: up to 2040 mg/kg).\r\nIngestion or contact with an excessive quantity of boron may harm the health of children by damaging the reproductive system.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-3.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28249-1s.jpg', '', NULL),
(93, 'Halonen', 'Create', 'Clothing, textiles and fashion items', 'China', '', 'Chemical', 'Chemical\r\nThere is an excessive amount of chromium (VI) in the leather insoles of both pair of shoes (measured value: 113.7 mg/kg and 19.7 mg/kg respectively).\r\nChromium (VI) is sensitising and may trigger allergic reactions.\r\n\r\nThe product does not comply with the REACH regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28241-1s.jpg', '', NULL),
(94, 'Unknown', 'Y-Clu', 'Clothing, textiles and fashion items', 'China', '', 'Injuries', 'Injuries\r\nThe product has drawstrings in the waist area, which are too long and unattached.\r\nThe drawstrings can become trapped during activities of the child and cause injuries. \r\n\r\nThe product does not comply with the applicable European Standard EN 14682. ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28226-1s.jpg', '', NULL),
(95, 'Unknown', 'Y-Clu', 'Clothing, textiles and fashion items', 'China', '', 'Injuries', 'Injuries\r\nThe product has drawstrings in the waist area, which are too long and unattached.\r\nThe drawstrings can become trapped during activities of the child and cause serious injuries.\r\n\r\nThe product does not comply with the relevant European Standard EN 14682. ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28228-1s.jpg', '', NULL),
(96, 'Unknown', 'Y-Clu', 'Clothing, textiles and fashion items', 'China', '', 'Injuries, Strangulation', 'Injuries, Strangulation\r\nThe product has drawstrings in the neck and back area.\r\nThe drawstrings may become trapped during various activities of a child, leading to strangulation or injuries.\r\n\r\nThe product does not comply with the relevant European standard EN 14682. ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28230-1s.jpg', '', NULL),
(97, 'Strawberry', 'Y-Clu', 'Clothing, textiles and fashion items', 'China', '', 'Injuries', 'Injuries\r\nThere are decorative cords with free ends in the upper chest area.\r\nThese cords may become trapped during various activities of the child, leading to injuries. \r\n\r\nThe product does not comply with the relevant European Standard EN 14682.\r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28229-1s.jpg', '', NULL),
(98, 'USB Power Adapter', 'Unknown', 'Electrical appliances and equipment', 'China', '', 'Electric shock', 'Electric shock\r\nThe electrical insulation and the creepage/clearance distances are inadequate.\r\nThe user may receive an electric shock from live parts.\r\n\r\nThe product does not comply with the requirements of the Low Voltage Directive and the relevant European standard EN 60950.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28231-1s.jpg', '', NULL),
(99, 'Unknown', 'Unknown', 'Electrical appliances and equipment', 'China', '', 'Electric shock, Fire', 'Electric shock, Fire\r\nThe product does not have shutters on live parts, nor a fuse.\r\nA user could consequently touch live parts of the socket and receive an electric shock.\r\n\r\nThe product does not comply with the relevant national standards. \r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28227-1s.jpg', '', NULL),
(100, 'NP Mesh Goggles', 'NUPROL PMC', 'Protective equipment', 'China', '', 'Injuries', 'Injuries\r\nThe goggles do not provide sufficient protection from projectiles launched at high speed and the mesh can detach.\r\nAs a result, the user''s eyes could get injured. \r\n\r\nThe product does not comply with the requirements of the Personal Protective Equipment Directive.\r\n ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2019/2019-w18/2019-w18_28054-1s.jpg', '', NULL);
INSERT INTO `tbl_ras_data` (`Id`, `Product_Name`, `Product_Brand`, `Product_Category`, `Country_Origin`, `City_Origin`, `Risk_Type`, `Description`, `Image_Path`, `transaction_hash`, `Model`) VALUES
(101, 'LED LIGHT 320L', 'Unknown', 'Lighting chains', 'China', '', 'Electric shock, Fire', 'Electric shock, Fire\r\nThe cross-sectional area of the external and internal wires is too small. This could cause the cable to overheat and lead to a fire.\r\nLive parts are accessible and, as a consequence, users might receive an electric shock when touching them.\r\n\r\nThe product does not comply with the requirements of the Low Voltage Directive and the relevant European standard EN 60598.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24916-1s.jpg', '', NULL),
(102, '200 LED MINILUCCIOLE LED', 'Unknown', 'Lighting chains', 'China', '', 'Electric shock, Fire', 'Electric shock, Fire\r\nThe cable is not properly anchored and is too thin. The accessible wires have only basic insulation.\r\nThe basic insulated cable could detach or become damaged leaving the live conductors accessible. It could also overheat leading to a fire.\r\n\r\nThe product does not comply with the requirements of the Low Voltage Directive and the relevant European standard EN 60598.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24929-1s.jpg', '', NULL),
(103, '200 LED MINILUCCIOLE LED', 'Unknown', 'Lighting chains', 'China', '', 'Electric shock, Fire', 'Electric shock, Fire\r\nThe cable is not properly anchored and is too thin. The accessible wires have only basic insulation.\r\nThe cable could detach or become damaged leaving the live conductors accessible. It could also overheat leading to a fire.\r\n\r\nThe product does not comply with the requirements of the Low Voltage Directive and the relevant European standard EN 60598.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24930-1s.jpg', '', NULL),
(104, 'Table Light', 'Unknown', 'Lighting equipment', 'China', '', 'Electric shock', 'Electric shock\r\nThe cable anchorage is inadequate.\r\nThe cable could detach leaving the live conductors accessible.\r\n\r\nThe product does not comply with the requirements of the Low Voltage Directive and the relevant European standard EN 60598.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24932-1s.jpg', '', NULL),
(105, 'Petrol Chain Saw', 'FIELDMANN', 'Machinery', 'China', '', 'Injuries', 'Injuries\r\nThe front hand-guard can break preventing the automatic application of the chain brake.\r\nIn the event of kickback, the user could suffer injuries from the moving chain.\r\n\r\nThe product does not comply with the requirements of the Machinery Directive and the relevant European standard EN 11681.\r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24934-1s.jpg', '', NULL),
(106, 'Scenic', 'Renault', 'Motor vehicles', 'France', '', 'Injuries', 'Injuries\r\nThe LED module for monitoring and managing the actuation of the rear lights of the trailer could be damaged.\r\nTotal failure of the rear lights of the trailer could occur.', NULL, '', NULL),
(107, '208', 'Peugeot', 'Motor vehicles', 'France', '', 'Injuries', 'Injuries\r\nThe front wheel axle assembly may be incorrectly tightened.\r\nThis may lead to a loss of connection between the steering and the front wheel axle, resulting in an accident causing injury to vehicle occupants or other road users.', NULL, '', NULL),
(108, 'DS3', 'Citroën', 'Motor vehicles', 'France', '', 'Injuries', 'Injuries\r\nThe front wheel axle assembly may be incorrectly tightened.\r\nThis may lead to a loss of connection between the steering and the front wheel axle, resulting in an accident causing injury to vehicle occupants or other road users..', NULL, '', NULL),
(109, 'RZR XP 1000 / XP4 1000', 'Polaris', 'Motor vehicles', 'United States', '', 'Fire, Injuries', 'Fire, Injuries\r\nThe heat shield may not adequately shield exhaust gasses in the event of an exhaust silencer crack.\r\nThis could lead to melting of nearby components, leading to injuries to the driver, and poses a fire hazard.', NULL, '', NULL),
(110, 'DUALFIX', 'Britax-Römer', 'Childcare articles and children''s equipment', 'China', '', 'Injuries', 'Injuries\r\nThere might be hairline cracks in both seat shell mountings.\r\nIn the event of an accident, this could lead to the child seat shell detaching from the base causing injuries to the child and vehicle passengers. \r\n\r\nThe product does not comply with UN/ECE Regulation No 44-04.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24917-1s.jpg', '', NULL),
(111, 'Pianka Puzzle/ Eva puzzle mats', 'Unknown', 'Toys', 'China', '', 'Choking', 'Choking\r\nThe mat has detachable small parts.\r\nSmall children could put the small parts in the mouth and choke on them.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and with the relevant European standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24885-1s.jpg', '', NULL),
(112, 'Blocs de Construction', 'Couleur bébé', 'Toys', 'China', '', 'Choking', 'Choking\r\nThe toy includes loose, small parts.\r\nA small child could put these small parts in the mouth and choke on them.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1 .', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24915-1s.jpg', '', NULL),
(113, 'JSA', 'Unknown', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe plastic material of the toy and its valve contain di-(2-ethylhexyl) phthalate (DEHP) (measured value up to 12.3% by weight).\r\nThis phthalate may harm the health of children, causing possible damage to the reproductive system.\r\n\r\nThe product does not comply with the REACH Regulation.\r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24919-1s.jpg', '', NULL),
(114, 'Animal raw eggs', 'P.H. KRIS TAEM/Happy farm', 'Toys', 'China', '', 'Choking', 'Choking\r\nThe toy contains small parts (plastic eggs).\r\nA child may put the small parts in the mouth and choke.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24928-1s.jpg', '', NULL),
(115, 'Maskotka/240', 'Unknown', 'Toys', 'China', '', 'Choking', 'Choking\r\nThe suction cup may detach from the toy.\r\nA child may put it in the mouth and choke.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24933-1s.jpg', '', NULL),
(116, 'Unknown', 'Boland', 'Clothing, textiles and fashion items', 'China', '', 'Chemical', 'Chemical\r\nThe amount of nickel released from the rivets connecting the rubber band to the mask is too high (measured value up to 5.27 µg/cm²/week).\r\nNickel is a strong sensitiser and can cause allergic reactions if present in articles that come into direct and prolonged contact with the skin. \r\n\r\nThe product does not comply with the REACH Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24908-1s.jpg', '', NULL),
(117, '‘Mon Mouton’ (‘my sheep’)', 'La Maison de Lilo', 'Clothing, textiles and fashion items', 'China', '', 'Strangulation', 'Strangulation\r\nThere are drawstrings in the hood of the jacket.\r\nThese can become trapped during various activities of a child, leading to strangulation.\r\nThe product does not comply with the relevant European Standard EN 14682.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24923-1s.jpg', '', NULL),
(118, 'Lederhose Tegernsee K13, kurz', 'Wiesnkönig', 'Clothing, textiles and fashion items', 'India', '', 'Chemical', 'Chemical\r\nThe amount of chromium (VI) in the leather is too high (measured value up to 10 mg/kg).\r\nChromium (VI) is sensitising and may trigger allergic reactions. \r\n\r\nThe product does not comply with the REACH regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24939-1s.jpg', '', NULL),
(119, 'ACTION Four', 'Shirley May', 'Cosmetics', 'United Arab Emirates', '', 'Chemical', 'Chemical\r\nThe perfume contains the following fragrances:\r\ncitronellol, geraniol, eugenol, alpha-isomethyl ionone and hydroxyisohexyl 3-cyclohexene carboxaldehyde (measured values: 0.0063 %, 0.0028 %, 0.0026 %, 0.0079 % and 0.0069 % by weight).\r\nSince these substances, which can induce allergic reactions and sensitisation, are not indicated in the list of ingredients, consumers are not aware of their presence.\r\n\r\nThe product does not comply with the Cosmetic Products Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24918-1s.jpg', '', NULL),
(120, 'My Fair Lady Brulee', 'Bomb cosmetics', 'Cosmetics', 'Unknown', '', 'Choking', 'Choking\r\nDue to its characteristic form, colour and size, the product may be mistaken for foodstuff.\r\nSmall parts can be easily detached or bitten off the product and this may lead children to put them in the mouth and choke.\r\n\r\nThe product does not comply with the Cosmetic Products Regulation and the requirements of the Food-imitating Products Directive.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24881-1s.jpg', '', NULL),
(121, 'Unknown', 'Bellelli', 'Childcare articles and children''s equipment', 'Italy', '', 'Injuries', 'Injuries\r\nIt might appear that the buckle of the seat belt is fully closed but it is not.\r\nThe non-fully closed buckle can be released during driving and the child can slide out of the seat.\r\n\r\nThe product does not comply with the relevant European standard EN 14344.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24911-1s.jpg', '', NULL),
(122, 'Unknown', 'GRACE', 'Clothing, textiles and fashion items', 'Unknown', '', 'Injuries', 'Injuries\r\nThe trousers have cords with toggles at the lower edge of the trouser legs, forming a loop.\r\nIt can become trapped during various activities of a child, e.g. when riding a bicycle, sliding on a slide or running, leading to injuries.\r\n\r\nThe product does not comply with the requirements of the General Product Safety Directive and the relevant European standard EN 14682.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2018/2018-w18/2018-w18_24876-1s.jpg', '', NULL),
(123, 'Unknown', 'Loresa', 'Furniture', 'Turkey', '', 'Cuts, Injuries', 'Cuts, Injuries\r\nThere are openings and sharp accessible parts and edges on the metal tubes which can cause injuries or cuts to the user when folding or unfolding the table.\r\n\r\nThe product does not comply with the relevant European Standard EN 581.\r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23355-1s.jpg', '', NULL),
(124, 'Unknown', 'Arslan', 'Furniture', 'Turkey', '', 'Cuts, Injuries', 'Cuts, Injuries\r\nThe metal tubes of the table are not strong enough and break easily. In addition, there are sharp accessible parts and edges on the tubes, which can cause cuts to the user when folding or unfolding the table.\r\n\r\nThe product does not comply with the European Standard EN 581 and EN 1730.\r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23354-1s.jpg', '', NULL),
(125, 'Unknown', 'Fashion Jewelry', 'Jewellery', 'China', '', 'Chemical', 'Chemical\r\nThe necklace contains cadmium.\r\n\r\nCadmium is harmful to human health because it accumulates in the body and can damage organs and may cause cancer.\r\n\r\nThe product does not comply with the REACH Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23374-1s.jpg', '', NULL),
(126, 'Riipuspidike putkimainen kukka', 'Helmien talo', 'Jewellery', 'China', '', 'Chemical', 'Chemical\r\nThe product contains cadmium (measured value 90 % by weight). Cadmium is harmful to human health, because it accumulates in the body and can damage organs and it may cause cancer.\r\n\r\nThe product does not comply with the REACH Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23393-1s.jpg', '', NULL),
(127, 'Atego', 'Mercedes-Benz', 'Motor vehicles', 'Germany', '', 'Injuries', 'Injuries\r\nDue to a manufacturing error, parts securing the fuel tank might break. As a result, the fuel tank might become detached from the vehicle and fall onto the road, endangering following vehicles.', NULL, '', NULL),
(128, 'G310R', 'BMW', 'Motor vehicles', 'India', '', 'Injuries', 'Injuries\r\nThe front brake caliper is not correctly secured and may come loose. ', NULL, '', NULL),
(129, 'X3, M6 Coupé, M6 Cabrio', 'BMW', 'Motor vehicles', 'Germany', '', 'Injuries', 'Injuries\r\nThe housing of the driver’s front airbag inflator may have been incorrectly welded. In the event of a crash with airbag activation, the inflator may consequently rupture. Metal fragments created as a result could pass through the airbag, causing fatal injuries to the vehicle occupants. ', NULL, '', NULL),
(130, 'CRF450R', 'Honda', 'Motor vehicles', 'Japan', '', 'Injuries', 'Injuries\r\nThe gearbox could fail without warning due to a defect with the countershaft gear. This could lead to an accident occurring.', NULL, '', NULL),
(131, 'Ibiza', 'SEAT', 'Motor vehicles', 'Spain', '', 'Injuries', 'Injuries\r\nThe tightening torque on the steering column bolt may be incorrect, which may result in a failure of the steering system and loss of control of the vehicle. ', NULL, '', NULL),
(132, 'R nineT', 'BMW', 'Motor vehicles', 'Germany', '', 'Injuries', 'Injuries\r\nThe screwed connection between the frame and the fixed bearing stud for the rear swinging arm may loosen, leading to reduced rear wheel guidance.', NULL, '', NULL),
(133, 'Ghibli, Levante, Quattroporte', 'Maserati', 'Motor vehicles', 'Italy', '', 'Fire', 'Fire\r\nThe seat cabling of the driver''s seat may be incorrectly installed. This can cause the seat cabling to rub against metal points of the seat and/or against the seat frame unit. Over time this could lead to an electrical short circuit which could cause a fire.\r\n', NULL, '', NULL),
(134, 'Einachs – Pritschenhochlader Tandem – Pritschenhochlader Absenkanhänger – Einachs Kofferanhänger – E', 'Sproll', 'Motor vehicles', 'Germany', '', 'Injuries', 'Injuries\r\nThe tyres are defective and could consequently deflate rapidly during use.', NULL, '', NULL),
(135, 'Actros, Arocs, Atego, Axor', 'Mercedes-Benz', 'Motor vehicles', 'Germany', '', 'Injuries', 'Injuries\r\nThe crimping of the brake hoses on the steered front axles, the steered leading and trailing axles can come loose. This could cause the braking action of the service brake, depending on the steered axle affected, to partially fail. If it fails on one side, the vehicle will yaw to the side when braking. In vehicles fitted with a front axle parking brake, the front wheel could also be blocked by the parking brake. This could increase the risk of accidents.\r\n', NULL, '', NULL),
(136, 'Liberty 50 iGet 4T 3V', 'Piaggio', 'Motor vehicles', 'Italy', '', 'Injuries', 'Injuries\r\nThere is a risk that the screw that holds the swing arm will be unscrewed which may cause loss of stability of vehicle during use and in consequence lead to an accident.', NULL, '', NULL),
(137, 'FLY 125 4T 3V ie', 'Piaggio', 'Motor vehicles', 'Italy', '', 'Injuries', 'Injuries\r\nThere is a risk that loosened retaining screws of brake disc may affect the brake’s efficiency. This may lead to an accident.', NULL, '', NULL),
(138, 'Mighty Knight', 'Unknown', 'Toys', 'China', '', 'Burns, Injuries, Strangulation', 'Burns, Injuries, Strangulation\r\nThe product poses a risk of burns due to the high flammability of the material of the hood. If the child wears the hood and it catches fire, the child may get burns mostly on the head and face. In addition, there are fixed loops in the hood and on the shoulders which can become trapped during various activities of the child, leading to injury or strangulation.\r\n\r\nThe product does not comply with the Toy Safety Directive and the relevant European standards EN 71-2 ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23363-1s.jpg', '', NULL),
(139, 'Spirit Gun - Weapony Power', 'Unknown', 'Toys', 'China', '', 'Choking', 'Choking\r\nThe suction cup of the  projectiles can easily detach. If a child puts the projectile in the mouth, the suction cup can detach, leaving the airways obstructed by it.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European Standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23368-1s.jpg', '', NULL),
(140, 'Shoots', 'Unknown', 'Toys', 'China', '', 'Choking', 'Choking\r\nThe suction cup of the projectiles can easily detach. If a child puts the projectile in the mouth, the suction cup can detach, leaving the airways obstructed by it.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European Standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23369-1s.jpg', '', NULL),
(141, 'Princess shoes', 'Girlz Club', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe plastic shoes contain di-(2-etylhexyl) phthalate (DEHP) (measured value ˃20% by weight) and di-(2-butyl) phthalate (DBP) (measured value up to 12% by weight). These phthalates may harm the health of children, causing possible damage to the reproductive system. \r\n\r\nAccording to the REACH Regulation the phthalates DEHP, DBP and BBP are prohibited in all toys and childcare articles.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23373-1s.jpg', '', NULL),
(142, 'Beauty set', 'Unknown', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe make-up contains nickel (measured value up to 45 mg/kg), arsenic (measured value 0.5 mg/kg), chromium (measured value up to 2.3 mg/kg) and lead (measured value up to 8.5 mg/kg). Nickel is a strong sensitizer and can cause allergic reactions if present in articles that come into direct and prolonged contact with the skin and arsenic is toxic.\r\n\r\nThe product does not comply with the Cosmetic Products Regulation.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23376-1s.jpg', '', NULL),
(143, 'Kostka [Dice]', 'Unknown', 'Toys', 'China', '', 'Choking', 'Choking\r\nSmall parts may easily be torn from the toy. A small child may put them in the mouth and choke.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standard EN 71-1.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23390-1s.jpg', '', NULL),
(144, 'Doctor Toy Set', 'Sudali Toys', 'Toys', 'China', '', 'Chemical', 'Chemical\r\nThe toys contain di-(2-etylhexyl) phthalate (DEHP) (measured value 4,3 % by weight) and di-(2-butyl) phthalate (DBP) (measured value 0.19% by weight). These phthalates may harm the health of children, causing possible damage to the reproductive system. \r\n\r\nAccording to the REACH Regulation, DEHP, DBP and BBP phthalates are prohibited in all toys and childcare articles.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23391-1s.jpg', '', NULL),
(145, 'Girls', 'Mango Kids', 'Clothing, textiles and fashion items', 'China', '', 'Strangulation', 'Strangulation\r\nThe functional cords designed to be tied at the chest can become trapped during various activities of the child, causing strangulation.\r\n\r\nThe product does not comply with the relevant European standard EN 14682.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23370-1s.jpg', '', NULL),
(146, 'Unknown', 'Zeeman', 'Clothing, textiles and fashion items', 'China', '', 'Chemical', 'Chemical\r\nThe product contains the azo dye Disperse Yellow 23 (CI 26070) releasing an excessive amount of the aromatic amine 4-aminoazobenzene (measured value: 567 mg/kg). When the product is in direct and prolonged contact with the skin, the aromatic amine may be absorbed by the skin. Aromatic amines can cause cancer, cell mutations and affect reproduction.\r\n\r\nThe product does not comply with the REACH Regulation.\r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23359-1s.jpg', '', NULL),
(147, 'Unknown', 'Ateş Böcegi', 'Clothing, textiles and fashion items', 'Turkey', '', 'Choking', 'Choking\r\nThe rhinestones can easily be detached and may be ingested by a small child, causing choking. ', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23380-1s.jpg', '', NULL),
(148, 'Unknown', 'Haizhongbao', 'Clothing, textiles and fashion items', 'Unknown', '', 'Injuries', 'Injuries\r\nThe cords in the waist area may become trapped during various activities of a child and cause injuries.\r\n\r\nThe product does not comply with the relevant European standard EN 14682.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23389-1s.jpg', '', NULL),
(149, 'Unknown', 'Baray', 'Clothing, textiles and fashion items', 'Turkey', '', 'Injuries, Strangulation', 'Injuries, Strangulation\r\nThe cords at the head, neck and shoulders area may become trapped during various activities of a child, leading to injuries or strangulation.\r\n\r\nThe product does not comply with the relevant European standard EN 14682. \r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23388-1s.jpg', '', NULL),
(150, 'Unknown', 'Trendy boy', 'Clothing, textiles and fashion items', 'China', '', 'Injuries', 'Injuries\r\nThe cords in the waist area may become trapped during various activities of the child, leading to injuries. \r\n\r\nThe product does not comply with the relevant European standard EN 14682.\r\n', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23387-1s.jpg', '', NULL),
(151, 'Clips custodia succhietto/Clip dummy holder', 'POUPY', 'Childcare articles and children''s equipment', 'Italy', '', 'Cuts', 'Cuts\r\nThe product has sharp edges which may injure the child when using the soother holder. \r\n\r\nThe product does not comply with the relevant European standard EN 12586.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23366-1s.jpg', '', NULL),
(152, 'Pokémon GO (may be counterfeit)', 'Unknown', 'Toys', 'China', '', 'Chemical, Choking', 'Chemical, Choking\r\nThe cover of the battery compartment can easily be opened without any tools and the batteries are accessible. They could cause damage to the child’s gastrointestinal tract if put in the mouth and swallowed.\r\n\r\nThe product does not comply with the requirements of the Toy Safety Directive and the relevant European standards EN 62115.', 'https://ec.europa.eu/consumers/consumers_safety/safety_products/rapex/alerts/repository/content/2017/2017-w36/2017-w36_23365-1s.jpg', '', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `tbl_report`
--

CREATE TABLE IF NOT EXISTS `tbl_report` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Product_Name` varchar(100) NOT NULL,
  `Product_Brand` varchar(100) NOT NULL,
  `Product_Category` varchar(45) NOT NULL,
  `Country_Origin` varchar(45) NOT NULL,
  `City_Origin` varchar(45) NOT NULL,
  `Risk_Type` varchar(45) NOT NULL,
  `Description` varchar(500) DEFAULT NULL,
  `Image_Path` varchar(500) DEFAULT NULL,
  `transaction_hash` varchar(100) NOT NULL,
  `Model` varchar(100) DEFAULT NULL,
  `User_ID` int(11) NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `fk_Report_User_idx` (`User_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=11 ;

--
-- Table structure for table `tbl_user`
--

CREATE TABLE IF NOT EXISTS `tbl_user` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `First_Name` varchar(45) NOT NULL,
  `Last_Name` varchar(45) NOT NULL,
  `Email` varchar(45) NOT NULL UNIQUE,
  `Street` varchar(45) NOT NULL,
  `City` varchar(45) NOT NULL,
  `Zip` varchar(45) NOT NULL,
  `Country` varchar(45) NOT NULL,
  `User_Name` varchar(45) NOT NULL,
  `Password` varchar(45) NOT NULL,
  `Description` varchar(240) DEFAULT NULL,
  `Gender` varchar(45) DEFAULT NULL,
  `Phone_Number` int(11) DEFAULT NULL,
  `Landline_number` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=8 ;


--
-- Constraints for table `tbl_report`
--
ALTER TABLE `tbl_report`
  ADD CONSTRAINT `fk_Report_User` FOREIGN KEY (`User_ID`) REFERENCES `tbl_user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
